"use client";
import { useEffect, useRef, useState } from "react";
import { z } from "zod";
import { BookOpen, CheckCircle2, Lightbulb, RotateCcw, Sparkles } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { lessons, type Language } from "@/lib/lessons";
const copyBase={
 ru:{eyebrow:"Математика • для студентов 18+",title:"Не заучивай. Разберись.",sub:"Одна тема, понятный пример и три вопроса. Учись на языке, на котором тебе легче думать.",note:"Маленькие шаги. Больше понимания.",topics:"Сегодня разберём",lesson:"Объяснение",practice:"Практика",ai:"Спросить Claude",rule:"Главная идея",example:"Разберём на примере",hint:"Попробуй объяснить каждый шаг своими словами, а затем проверь себя.",check:"Проверить ответы",reset:"Попробовать снова",correct:"Верно",wrong:"Давай разберём",result:"Ваш результат",choose:"Ответьте на все три вопроса.",session:"Ответы сохраняются только до смены темы или закрытия страницы.",aiTitle:"Что осталось непонятным?",aiSub:"Claude объяснит выбранную тему другим способом. Ответ может содержать ошибки — сверяйте вычисления.",question:"Ваш вопрос по этой теме",placeholder:"Например: почему нужно вычитать одно число с обеих сторон?",adult:"Мне исполнилось 18 лет.",consent:"Разрешаю передать текст вопроса Anthropic для ответа Claude. Не отправляю личные данные.",ask:"Получить объяснение",loading:"Готовим объяснение…",pilot:"Claude доступен только участникам закрытого пилота после подключения API. Учебные примеры и тесты работают без него.",signin:"Войти для пилота",read:"О проекте",privacy:"Данные и приватность",foot:"Ранний MVP · без платных подписок",static:"Подготовленный учебный пример · не ответ AI",next:"Повтори ошибочные шаги и пройди тест ещё раз.",done:"Отлично. Перейди к следующей теме."},
 uz:{eyebrow:"Matematika • 18+ talabalar uchun",title:"Yodlama. Tushunib ol.",sub:"Bitta mavzu, tushunarli misol va uchta savol. Fikrlash osonroq bo‘lgan tilda o‘rganing.",note:"Kichik qadamlar. Chuqurroq tushunish.",topics:"Bugungi mavzular",lesson:"Tushuntirish",practice:"Mashq",ai:"Claude’dan so‘rash",rule:"Asosiy fikr",example:"Misol orqali o‘rganamiz",hint:"Har bir qadamni o‘z so‘zlaringiz bilan tushuntiring, keyin o‘zingizni tekshiring.",check:"Javoblarni tekshirish",reset:"Yana urinib ko‘rish",correct:"To‘g‘ri",wrong:"Birga ko‘rib chiqamiz",result:"Natijangiz",choose:"Uchala savolga javob bering.",session:"Javoblar mavzu o‘zgarguncha yoki sahifa yopilguncha saqlanadi.",aiTitle:"Nima tushunarsiz qoldi?",aiSub:"Claude mavzuni boshqa usulda tushuntiradi. Javobda xatolar bo‘lishi mumkin — hisoblarni tekshiring.",question:"Mavzu bo‘yicha savolingiz",placeholder:"Masalan: nega ikkala tomondan bir xil sonni ayirish kerak?",adult:"Men 18 yoshga to‘lganman.",consent:"Claude javob berishi uchun savolimni Anthropic’ga yuborishga roziman. Shaxsiy ma’lumot yubormayman.",ask:"Tushuntirish olish",loading:"Tushuntirish tayyorlanmoqda…",pilot:"Claude API ulanganidan so‘ng faqat yopiq sinov ishtirokchilariga ochiladi. Dars va testlar usiz ishlaydi.",signin:"Sinov uchun kirish",read:"Loyiha haqida",privacy:"Ma’lumotlar va maxfiylik",foot:"Ilk MVP · pulli obunalar yo‘q",static:"Tayyorlangan dars · AI javobi emas",next:"Xato qadamlarni takrorlang va testni yana bajaring.",done:"Ajoyib. Keyingi mavzuga o‘ting."}
};
const copy={...copyBase,kk:{eyebrow:"Математика • 18+ студенттерге",title:"Жаттама. Түсініп ал.",sub:"Бір тақырып, түсінікті мысал және үш сұрақ. Ойлануға ыңғайлы тілде оқыңыз.",note:"Шағын қадамдар. Тереңірек түсіну.",topics:"Бүгінгі тақырыптар",lesson:"Түсіндіру",practice:"Жаттығу",ai:"Claude-тан сұрау",rule:"Негізгі ой",example:"Мысал арқылы үйренеміз",hint:"Әр қадамды өз сөзіңізбен түсіндіріңіз, содан кейін өзіңізді тексеріңіз.",check:"Жауаптарды тексеру",reset:"Қайта байқап көру",correct:"Дұрыс",wrong:"Бірге талдайық",result:"Нәтижеңіз",choose:"Үш сұрақтың бәріне жауап беріңіз.",session:"Жауаптар тақырып ауысқанға немесе бет жабылғанға дейін сақталады.",aiTitle:"Не түсініксіз қалды?",aiSub:"Claude тақырыпты басқа тәсілмен түсіндіреді. Жауапта қате болуы мүмкін — есептерді тексеріңіз.",question:"Тақырып бойынша сұрағыңыз",placeholder:"Мысалы: неге екі жақтан бірдей санды азайту керек?",adult:"Мен 18 жасқа толдым.",consent:"Claude жауап беруі үшін сұрағымды Anthropic-ке жіберуге келісемін. Жеке деректерді жібермеймін.",ask:"Түсіндіру алу",loading:"Жауап дайындалып жатыр…",pilot:"API қосылған соң Claude тек жабық сынақ қатысушыларына қолжетімді. Дайын сабақтар мен тесттер онсыз жұмыс істейді.",signin:"Сынақ үшін кіру",read:"Жоба туралы",privacy:"Деректер және құпиялық",foot:"Алғашқы MVP · ақылы жазылым жоқ",static:"Дайын оқу мысалы · AI жауабы емес",next:"Қате қадамдарды қайталап, тестті қайта өтіңіз.",done:"Жақсы. Келесі тақырыпқа өтіңіз."}};
type WebContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
export default function Study(){
 const [lang,setLang]=useState<Language>("ru"),[topic,setTopic]=useState("linear"),[tab,setTab]=useState("lesson");
 const [answers,setAnswers]=useState<Record<number,string>>({}),[checked,setChecked]=useState(false);
 const [question,setQuestion]=useState(""),[adult,setAdult]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[answer,setAnswer]=useState<{explanation:string;hint:string}|null>(null);
 const controller=useRef<AbortController|null>(null),generation=useRef(0);
 const lesson=lessons[lang].find(l=>l.id===topic)!,t=copy[lang],score=lesson.questions.filter((q,i)=>answers[i]===String(q.correct)).length;
 const current=useRef({topic,language:lang});current.current={topic,language:lang};
 useEffect(()=>{document.documentElement.lang=lang;},[lang]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:WebContext}).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();try{Promise.resolve(ctx.registerTool({name:"get_current_lesson",description:"Read the mathematics lesson currently visible in BilimAI. Does not send anything to Claude.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input || typeof input!=="object" || Array.isArray(input) || Object.keys(input).length)throw new Error("Expected an empty object");const state=current.current;const l=lessons[state.language].find(x=>x.id===state.topic)!;return {topic:state.topic,language:state.language,title:l.title,rule:l.rule};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);
 useEffect(()=>()=>controller.current?.abort(),[]);
 function reset(){generation.current++;controller.current?.abort();setAnswers({});setChecked(false);setAnswer(null);setError("");setBusy(false);setQuestion("");}
 function selectTopic(id:string){reset();setTopic(id);setTab("lesson");}
 function selectLanguage(value:Language){reset();setLang(value);}
 async function ask(){if(busy || !adult || !consent || question.trim().length<3)return;const version=generation.current;controller.current=new AbortController();setBusy(true);setError("");setAnswer(null);try{const res=await fetch("/api/explain",{method:"POST",headers:{"content-type":"application/json"},signal:controller.current.signal,body:JSON.stringify({topic,language:lang,question,adult,consent})});const data=z.object({error:z.string().optional(),explanation:z.string().optional(),hint:z.string().optional()}).parse(await res.json());if(version!==generation.current)return;if(!res.ok){const codes:Record<string,string>=lang==="ru"?{signin:"Войдите через ChatGPT для участия в пилоте.",pilot:"Ваш аккаунт пока не включён в закрытый пилот.",not_configured:"Claude пока не подключён. Используйте готовый урок и практику.",quota:"Лимит пилота исчерпан. Продолжите с готовыми уроками.",origin:"AI временно недоступен: требуется настройка адреса сайта."}:lang==="kk"?{signin:"Сынақ үшін ChatGPT арқылы кіріңіз.",pilot:"Аккаунтыңыз жабық сынаққа қосылмаған.",not_configured:"Claude әзірше қосылмаған. Дайын сабақтарды қолданыңыз.",quota:"Сынақ лимиті аяқталды. Дайын сабақтарды жалғастырыңыз.",origin:"Сайт мекенжайын баптау қажет."}:{signin:"Sinov uchun ChatGPT orqali kiring.",pilot:"Hisobingiz hali yopiq sinovga qo‘shilmagan.",not_configured:"Claude hali ulanmagan. Tayyor dars va mashqlardan foydalaning.",quota:"Sinov limiti tugadi. Tayyor darslarni davom ettiring."};throw new Error(codes[data.error??""]??(lang==="ru"?"Не удалось получить ответ. Попробуйте позже.":lang==="kk"?"Жауап алынбады. Кейінірек қайталаңыз.":"Javob olinmadi. Keyinroq urinib ko‘ring."));}if(!data.explanation || !data.hint)throw new Error("Invalid response");setAnswer({explanation:data.explanation,hint:data.hint});}catch(e){if(version===generation.current && !(e instanceof Error && e.name==="AbortError"))setError(e instanceof Error?e.message:"Ошибка сети");}finally{if(version===generation.current)setBusy(false);}}
 return <><header className="wrap top"><a className="brand" href="/"><img src="/favicon.svg" alt=""/>BilimAI <span className="beta">MVP</span></a><nav className="topnav" aria-label="Навигация"><a href="/about">{t.read}</a><div className="flex gap-1" aria-label="Язык"><Button variant={lang==="ru"?"default":"ghost"} size="sm" aria-pressed={lang==="ru"} onClick={()=>selectLanguage("ru")}>Русский</Button><Button variant={lang==="kk"?"default":"ghost"} size="sm" aria-pressed={lang==="kk"} onClick={()=>selectLanguage("kk")}>Қазақша</Button><Button variant={lang==="uz"?"default":"ghost"} size="sm" aria-pressed={lang==="uz"} onClick={()=>selectLanguage("uz")}>O‘zbekcha</Button></div></nav></header>
 <main className="wrap"><section className="hero"><div><span className="eyebrow">{t.eyebrow}</span><h1>{t.title}</h1><p>{t.sub}</p></div><div className="hero-note"><Lightbulb size={24} className="mb-2 text-primary"/>{t.note}</div></section>
 <section className="lab-launch"><div><strong>{lang==="ru"?"Найди ошибку. Проверь понимание.":lang==="kk"?"Қатені тап. Түсінгеніңді тексер.":"Xatoni top. Tushunishni tekshir."}</strong><span className="small">{lang==="ru"?"Разбор неверного шага и новая задача без подсказок — бесплатно.":lang==="kk"?"Қате қадамды талдап, жаңа есепті көмексіз шешіңіз — тегін.":"Xato qadamni tahlil qil va yangi masalani yordamsiz yech — bepul."}</span></div><a href={`/lab?lang=${lang}`}>{lang==="ru"?"В лабораторию →":lang==="kk"?"Зертханаға →":"Laboratoriyaga →"}</a></section><div className="workspace"><aside className="topics"><h2>{t.topics}</h2>{lessons[lang].map((l,i)=><button key={l.id} className={`topic ${topic===l.id?"active":""}`} aria-pressed={topic===l.id} onClick={()=>selectTopic(l.id)}><span className="num">0{i+1}</span><span className="topic-title">{l.title}</span></button>)}<div className="aside-note"><BookOpen size={22} className="mb-3"/>{t.static}<p>{lang==="ru"?"3 темы · 9 заданий · 3 языка":lang==="kk"?"3 тақырып · 9 тапсырма · 3 тіл":"3 mavzu · 9 topshiriq · 3 til"}</p></div></aside>
 <section className="surface" aria-label={lesson.title}><div className="lesson-head"><div><h2>{lesson.title}</h2><p className="small mt-1 mb-0">{lesson.intro}</p></div><span className="small">{lang==="ru"?"Основы":lang==="kk"?"Негіздер":"Asoslar"}</span></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="tabsbar h-auto flex-wrap justify-start"><TabsTrigger value="lesson">{t.lesson}</TabsTrigger><TabsTrigger value="practice">{t.practice}</TabsTrigger><TabsTrigger value="ai"><Sparkles size={15}/>{t.ai}</TabsTrigger></TabsList>
 <TabsContent value="lesson"><div className="rule"><strong>{t.rule}</strong>{lesson.rule}</div><h3 className="text-lg mt-7 font-semibold">{t.example}</h3><div className="equation">{lesson.example}</div><ol className="steps">{lesson.steps.map((step,i)=><li key={step}><span className="step-number">{i+1}</span><span>{step}</span></li>)}</ol><div className="callout">{t.hint}</div><div className="actions"><Button onClick={()=>setTab("practice")}>{t.practice}</Button><span className="small">{t.static}</span></div></TabsContent>
 <TabsContent value="practice"><p className="small">{t.session}</p>{lesson.questions.map((q,i)=><div className="question" key={q.text}><h3 id={`q${i}`}>{i+1}. {q.text}</h3><RadioGroup aria-labelledby={`q${i}`} value={answers[i]??""} disabled={checked} onValueChange={v=>setAnswers(prev=>({...prev,[i]:v}))}>{q.options.map((option,j)=><label className="option" key={option} data-selected={answers[i]===String(j)}><RadioGroupItem value={String(j)} id={`q${i}a${j}`}/><span>{option}</span></label>)}</RadioGroup>{checked&&<div className={`feedback ${answers[i]!==String(q.correct)?"wrong":""}`}><strong>{answers[i]===String(q.correct)?t.correct:t.wrong}. </strong>{q.why}</div>}</div>)}<div className="actions">{checked?<><span role="status" className="score">{t.result}: {score}/3</span><Button variant="outline" onClick={()=>{setAnswers({});setChecked(false);}}><RotateCcw size={16}/>{t.reset}</Button></>:<Button disabled={Object.keys(answers).length!==3} onClick={()=>setChecked(true)}><CheckCircle2 size={16}/>{t.check}</Button>}</div><p className="small">{checked?(score===3?t.done:t.next):t.choose}</p></TabsContent>
 <TabsContent value="ai"><h3 className="text-xl font-semibold">{t.aiTitle}</h3><p className="small mb-5">{t.aiSub}</p><div className="callout mb-5">{t.pilot} <a href="/signin-with-chatgpt?return_to=%2F" target="_top">{t.signin}</a></div><form className="ai-form" onSubmit={e=>{e.preventDefault();void ask();}}><label htmlFor="learner-question">{t.question}</label><textarea id="learner-question" value={question} maxLength={600} minLength={3} required placeholder={t.placeholder} onChange={e=>setQuestion(e.target.value)}/><span className="small">{question.length}/600</span><label className="checkline"><Checkbox checked={adult} onCheckedChange={v=>setAdult(v===true)}/><span>{t.adult}</span></label><label className="checkline"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>{t.consent} <a href="/privacy">{t.privacy}</a></span></label><Button type="submit" disabled={busy||!adult||!consent||question.trim().length<3}>{busy?t.loading:t.ask}</Button></form>{error&&<p role="alert" className="error">{error}</p>}{answer&&<section aria-live="polite" className="response"><strong>Claude · AI</strong><p>{answer.explanation}</p><strong>{lang==="ru"?"Подсказка":lang==="kk"?"Көмек":"Yordam"}</strong><p>{answer.hint}</p></section>}</TabsContent>
 </Tabs></section></div></main><footer className="wrap foot"><span>BilimAI · {t.foot}</span><div><a href="/about">{t.read}</a><a href="/privacy">{t.privacy}</a></div></footer></>;
}


