"use client";
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { makeChallenge, checkAnswer, parseNumericAnswer, progressSchema, recommendTopic, topicName } from '@/lib/error-lab';
import type { LabTopic, Progress } from '@/lib/error-lab';
import type { Language } from '@/lib/lessons';

const labels={
 ru:{back:'К урокам',tag:'Лаборатория ошибок · 18+',title:'Ошибка — начало понимания.',intro:'Найди первый неверный шаг. Разберись в причине. Проверь себя на новой задаче.',static:'Подготовленные задания · без AI и оплаты',find:'1. Найди первый неверный шаг',check:'Проверить шаг',choose:'Выберите шаг',miss:'Это не первый неверный шаг. Проверь переходы по порядку.',reason:'Почему это ошибка',repair:'Правильный ход',transfer:'2. Реши новую задачу',answer:'Ваш ответ',format:'Число, десятичная дробь или дробь вида 3/7. Для вероятности можно указать проценты.',verify:'Проверить ответ',hint:'Подсказка',reveal:'Показать решение',invalid:'Введите число или дробь с ненулевым знаменателем.',wrong:'Пока не совпало. Проверь вычисления или возьми подсказку.',right:'Верно. Новая задача решена.',guided:'Решено после повторной попытки или с подсказкой. Повтори позже самостоятельно.',solo:'Решено с первой попытки без подсказок.',next:'Другая задача',progress:'Маршрут повторения',memory:'Сохранять результаты на этом устройстве',privacy:'Сохраняются только тема, номер задания, результат и дата. Без имени и текста ответов; последние 60 результатов. На общем устройстве лучше не включать.',clear:'Удалить сохранённые результаты',empty:'Начни с любой темы. После решения появится рекомендация.',recommend:'Следующий шаг',count:'разных задач без подсказок',limit:'Это результаты практики, а не оценка полного освоения темы. 24 варианта на тему; затем варианты повторяются.',storage:'Браузер не разрешил сохранение. Практика продолжит работать без него.',solved:'Решение',reset:'Удалено. Результаты текущей сессии сброшены.'},
 kk:{back:'Сабақтарға',tag:'Қателер зертханасы · 18+',title:'Қате — түсінудің бастауы.',intro:'Алғашқы қате қадамды тап. Себебін түсін. Жаңа есеппен өзіңді тексер.',static:'Дайын тапсырмалар · AI және төлем жоқ',find:'1. Алғашқы қате қадамды тап',check:'Қадамды тексеру',choose:'Қадамды таңдаңыз',miss:'Бұл алғашқы қате қадам емес. Қадамдарды ретімен тексеріңіз.',reason:'Бұл неге қате',repair:'Дұрыс жол',transfer:'2. Жаңа есепті шеш',answer:'Жауабыңыз',format:'Сан, ондық бөлшек немесе 3/7 түріндегі бөлшек. Ықтималдықты пайызбен де беруге болады.',verify:'Жауапты тексеру',hint:'Көмек',reveal:'Шешімді көрсету',invalid:'Сан немесе бөлімі нөл емес бөлшек енгізіңіз.',wrong:'Әзірше сәйкес емес. Есепті тексеріңіз немесе көмек алыңыз.',right:'Дұрыс. Жаңа есеп шешілді.',guided:'Көмекпен шешілді — кейін көмексіз қайталаңыз.',solo:'Бірінші әрекетте көмексіз шешілді.',next:'Басқа есеп',progress:'Қайталау бағыты',memory:'Нәтижелерді осы құрылғыда сақтау',privacy:'Тек тақырып, тапсырма нөмірі, нәтиже және күн сақталады. Аты-жөніңіз бен жауап мәтіні сақталмайды; соңғы 60 нәтиже. Ортақ құрылғыда қоспаған дұрыс.',clear:'Сақталған нәтижелерді жою',empty:'Кез келген тақырыптан бастаңыз. Шешкен соң ұсыныс пайда болады.',recommend:'Келесі қадам',count:'көмексіз шешілген әртүрлі есеп',limit:'Бұл жаттығу нәтижесі, тақырыпты толық меңгеру бағасы емес. Әр тақырыпта 24 нұсқа бар; кейін қайталанады.',storage:'Браузер сақтауға рұқсат бермеді. Жаттығу сақтаусыз жұмыс істейді.',solved:'Шешім',reset:'Жойылды. Осы сессия нәтижелері тазартылды.'},
 uz:{back:'Darslarga',tag:'Xatolar laboratoriyasi · 18+',title:'Xato — tushunishning boshlanishi.',intro:'Birinchi xato qadamni top. Sababini tushun. Yangi masala bilan o‘zingni tekshir.',static:'Tayyor topshiriqlar · AI va to‘lovsiz',find:'1. Birinchi xato qadamni top',check:'Qadamni tekshirish',choose:'Qadamni tanlang',miss:'Bu birinchi xato qadam emas. Qadamlarni tartib bilan tekshiring.',reason:'Nega bu xato',repair:'To‘g‘ri yo‘l',transfer:'2. Yangi masalani yech',answer:'Javobingiz',format:'Son, o‘nli kasr yoki 3/7 shaklidagi kasr. Ehtimollikni foizda ham yozish mumkin.',verify:'Javobni tekshirish',hint:'Yordam',reveal:'Yechimni ko‘rsatish',invalid:'Son yoki maxraji noldan farqli kasr kiriting.',wrong:'Hali mos kelmadi. Hisobni tekshiring yoki yordam oling.',right:'To‘g‘ri. Yangi masala yechildi.',guided:'Yordam bilan yechildi — keyin yordamsiz qaytaring.',solo:'Birinchi urinishda yordamsiz yechildi.',next:'Boshqa masala',progress:'Takrorlash yo‘li',memory:'Natijalarni shu qurilmada saqlash',privacy:'Faqat mavzu, topshiriq raqami, natija va sana saqlanadi. Ism va javob matni saqlanmaydi; oxirgi 60 natija. Umumiy qurilmada yoqmagan ma’qul.',clear:'Saqlangan natijalarni o‘chirish',empty:'Istalgan mavzudan boshlang. Yechgandan keyin tavsiya paydo bo‘ladi.',recommend:'Keyingi qadam',count:'yordamsiz yechilgan turli masala',limit:'Bu mashq natijasi, mavzuni to‘liq o‘zlashtirish bahosi emas. Har mavzuda 24 variant; keyin takrorlanadi.',storage:'Brauzer saqlashga ruxsat bermadi. Mashq saqlashsiz ishlaydi.',solved:'Yechim',reset:'O‘chirildi. Shu sessiya natijalari tozalandi.'}
};
const storageKey='bilimai-lab-v1';
const initialProgress:Progress={version:1,records:[]};
const topics:LabTopic[]=['linear','percent','probability'];
export default function ErrorLab(){
 const [lang,setLang]=useState<Language>('ru'),[topic,setTopic]=useState<LabTopic>('linear'),[seed,setSeed]=useState(0);
 const [selection,setSelection]=useState<number|null>(null),[found,setFound]=useState(false),[stepWrong,setStepWrong]=useState(false);
 const [input,setInput]=useState(''),[hints,setHints]=useState(0),[tries,setTries]=useState(0),[solved,setSolved]=useState(false),[revealed,setRevealed]=useState(false),[message,setMessage]=useState('');
 const [progress,setProgress]=useState<Progress>(initialProgress),[persist,setPersist]=useState(false),[storageError,setStorageError]=useState(false),[loaded,setLoaded]=useState(false);
 const c=makeChallenge(topic,seed,lang),t=labels[lang];
 useEffect(()=>{document.documentElement.lang=lang;},[lang]);
 useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw){const parsed=progressSchema.safeParse(JSON.parse(raw));if(parsed.success){setProgress(parsed.data);setPersist(true);}else localStorage.removeItem(storageKey);}}catch{setStorageError(true);}setLoaded(true);},[]);
 useEffect(()=>{if(!loaded)return;try{if(persist)localStorage.setItem(storageKey,JSON.stringify(progress));else localStorage.removeItem(storageKey);}catch{setStorageError(true);}},[persist,progress,loaded]);
 function reset(){setSelection(null);setFound(false);setStepWrong(false);setInput('');setHints(0);setTries(0);setSolved(false);setRevealed(false);setMessage('');}
 function changeTopic(value:LabTopic){reset();setTopic(value);setSeed(progress.records.filter(r=>r.topic===value).length);}
 function verify(){if(solved||revealed)return;if(parseNumericAnswer(input)===null){setMessage('invalid');return;}const correct=checkAnswer(input,c.answer);setTries(tries+1);if(!correct){setMessage('wrong');return;}setSolved(true);setMessage('right');setProgress(p=>({version:1,records:[...p.records,{topic,challenge:c.id,independent:hints===0&&tries===0,date:new Date().toISOString()}].slice(-60)}));}
 function clear(){try{localStorage.removeItem(storageKey);setPersist(false);setProgress(initialProgress);reset();}catch{setStorageError(true);}}
 return <><header className="wrap top"><a className="brand" href="/">BilimAI <span className="beta">LAB</span></a><nav className="topnav" aria-label="Language"><a href="/">{t.back}</a><div className="flex gap-1">{(['ru','kk','uz'] as Language[]).map(l=><Button key={l} size="sm" variant={lang===l?'default':'ghost'} aria-pressed={lang===l} onClick={()=>setLang(l)}>{l==='ru'?'Русский':l==='kk'?'Қазақша':'O‘zbekcha'}</Button>)}</div></nav></header>
 <main className="wrap"><section className="hero"><div><span className="eyebrow">{t.tag}</span><h1>{t.title}</h1><p>{t.intro}</p></div><div className="hero-note">{t.static}</div></section>
 <div className="lab-layout"><section className="surface"><div className="lab-topics">{topics.map(id=><Button key={id} variant={id===topic?'default':'outline'} aria-pressed={topic===id} onClick={()=>changeTopic(id)}>{topicName(id,lang)}</Button>)}</div><h2 className="lab-heading">{t.find}</h2><p className="lab-task">{c.task}</p>
 <div role="group" aria-label={t.choose} className="lab-steps">{c.steps.map((step,i)=><button key={i} disabled={found} className={`lab-step ${selection===i?'selected':''}`} aria-pressed={selection===i} onClick={()=>{setSelection(i);setStepWrong(false);}}><span className="step-number">{i+1}</span><span>{step}</span></button>)}</div>
 {!found&&<div className="actions"><Button disabled={selection===null} onClick={()=>{if(selection===c.wrongStep){setFound(true);setStepWrong(false);}else setStepWrong(true);}}>{t.check}</Button></div>}
 {stepWrong&&<p className="feedback wrong" role="status">{t.miss}</p>}
 {found&&<><div className="callout" role="status"><strong>{t.reason}</strong><p>{c.explanation}</p><strong>{t.repair}</strong><p className="lab-math">{c.repair}</p></div><h2 className="lab-heading">{t.transfer}</h2><p className="lab-task">{c.transfer}</p><form onSubmit={e=>{e.preventDefault();verify();}}><label htmlFor="lab-answer" className="lab-answer-label">{t.answer} {c.unit}</label><input id="lab-answer" className="lab-input" value={input} maxLength={48} disabled={solved||revealed} autoComplete="off" aria-describedby="answer-format" onChange={e=>{setInput(e.target.value);setMessage('');}}/><p id="answer-format" className="small">{t.format}</p><div className="actions"><Button type="submit" disabled={!input.trim()||solved||revealed}>{t.verify}</Button><Button type="button" variant="outline" disabled={hints>=3||solved||revealed} onClick={()=>setHints(v=>v+1)}>{t.hint} {hints}/3</Button><Button type="button" variant="ghost" disabled={solved||revealed} onClick={()=>{setRevealed(true);setMessage('');}}>{t.reveal}</Button></div></form>
 {hints>0&&<ol className="callout">{c.hints.slice(0,hints).map(h=><li key={h}>{h}</li>)}</ol>}
 {message&&<p role="status" className={`feedback ${message==='wrong'||message==='invalid'?'wrong':''}`}>{t[message as keyof typeof t]}{solved&&<> {hints===0&&tries===1?t.solo:t.guided}</>}</p>}
 {(solved||revealed)&&<div className="callout"><strong>{t.solved}</strong><p className="lab-math">{c.solution}</p><Button onClick={()=>{reset();setSeed(s=>s+1);}}>{t.next}</Button></div>}</>}
 </section><aside className="surface lab-progress"><h2>{t.progress}</h2>{progress.records.length===0?<p className="small">{t.empty}</p>:<><p className="small">{t.recommend}</p><Button variant="outline" onClick={()=>changeTopic(recommendTopic(progress))}>{topicName(recommendTopic(progress),lang)}</Button></>}
 <ul>{topics.map(id=><li key={id}><span>{topicName(id,lang)}</span><strong>{new Set(progress.records.filter(r=>r.topic===id&&r.independent).map(r=>r.challenge)).size}</strong></li>)}</ul><p className="small">{t.count}. {t.limit}</p><label className="checkline"><input type="checkbox" checked={persist} onChange={e=>setPersist(e.target.checked)}/><span>{t.memory}</span></label><p className="small">{t.privacy}</p><Button size="sm" variant="outline" onClick={clear}>{t.clear}</Button>{storageError&&<p role="status" className="small">{t.storage}</p>}</aside></div>
 </main><footer className="wrap foot"><span>{t.static}</span><a href="/privacy">{lang==='ru'?'Данные и приватность':lang==='kk'?'Деректер және құпиялық':'Ma’lumotlar va maxfiylik'}</a></footer></>;
}
