export type Language = "ru" | "uz" | "kk";
export type Lesson = { id: string; title: string; intro: string; rule: string; example: string; steps: string[]; questions: { text: string; options: string[]; correct: number; why: string }[] };
export const lessons: Record<Language, Lesson[]> = {
  kk: [
    {id:"linear",title:"Сызықтық теңдеулер",intro:"Екі жақтың теңдігін сақтап, белгісіз санды табамыз.",rule:"Теңдеудің екі жағына бірдей амал қолданамыз. Тек нөлден өзге санға бөлуге болады.",example:"3x + 6 = 21",steps:["Екі жақтан 6-ны азайтамыз: 3x = 15.","Екі жақты 3-ке бөлеміз: x = 5.","Тексереміз: 3 × 5 + 6 = 21."],questions:[{text:"2x + 4 = 14. x неге тең?",options:["3","5","7"],correct:1,why:"4-ті азайтамыз: 2x = 10. 2-ге бөлеміз: x = 5."},{text:"5x − 10 = 15. x-ті табыңыз.",options:["1","3","5"],correct:2,why:"10-ды қосамыз: 5x = 25. 5-ке бөлеміз: x = 5."},{text:"Қай амал теңдікті сақтайды?",options:["Тек сол жаққа 4 қосу","Екі жақтан 4 азайту","Екі жақты нөлге бөлу"],correct:1,why:"Екі жаққа бірдей рұқсат етілген амал қолдану теңдікті сақтайды. Нөлге бөлу анықталмаған."}]},
    {id:"percent",title:"Пайыздар",intro:"Пайызды үлеске айналдырып, бағаның өзгерісін есептейміз.",rule:"N санының p пайызы — N × p / 100. p% жеңілдіктен кейін бастапқы бағаның (100 − p)% бөлігі қалады.",example:"200 000 теңге бағасына 15% жеңілдік",steps:["Жеңілдік: 200 000 × 15 / 100 = 30 000 теңге.","Соңғы баға: 200 000 − 30 000 = 170 000 теңге.","Тексеру: 200 000-ның 85 пайызы = 170 000 теңге."],questions:[{text:"150-дің 20 пайызы нешеге тең?",options:["20","30","120"],correct:1,why:"150 × 20 / 100 = 30."},{text:"Баға 100 000 теңге, жеңілдік 10%. Қанша төлейсіз?",options:["10 000 теңге","90 000 теңге","110 000 теңге"],correct:1,why:"Жеңілдік 10 000 теңге. 100 000 − 10 000 = 90 000 теңге."},{text:"Баға 80-нен 100-ге өсті. Неше пайызға?",options:["20%","25%","80%"],correct:1,why:"Өсім 20. Бастапқы баға 80: 20 / 80 × 100 = 25%."}]},
    {id:"probability",title:"Ықтималдық",intro:"Нәтижелердің мүмкіндігі бірдей болғанда ықтималдықты есептейміз.",rule:"Ықтималдық = қолайлы нәтижелер саны / мүмкіндігі бірдей барлық нәтижелер саны. Мәні 0 мен 1 аралығында.",example:"Әділ ойын сүйегінде жұп сан түсуі",steps:["Мүмкіндігі бірдей 6 нәтиже бар: 1, 2, 3, 4, 5, 6.","Қолайлы 3 нәтиже: 2, 4, 6.","Ықтималдық: 3 / 6 = 1 / 2 = 50%."],questions:[{text:"Әділ ойын сүйегінде 6 түсу ықтималдығы?",options:["1/2","1/6","1/3"],correct:1,why:"Алты нәтижеден біреуі қолайлы: 1/6."},{text:"Қапта 3 қызыл және 2 көк шар бар. Кездейсоқ алынған шардың көк болу ықтималдығы?",options:["2/3","3/5","2/5"],correct:2,why:"Барлығы 5 шар, көк шар саны 2: ықтималдық 2/5."},{text:"Ықтималдық 1,2 болуы мүмкін бе?",options:["Иә","Жоқ"],correct:1,why:"Ықтималдық 1-ден үлкен болмайды. 1 — міндетті түрде болатын оқиға."}]}
  ],
  ru: [
    { id: "linear", title: "Линейные уравнения", intro: "Находим неизвестное, сохраняя равенство двух сторон.", rule: "С обеими сторонами выполняем одно и то же действие. Делить можно только на ненулевое число.", example: "3x + 6 = 21", steps: ["Вычтем 6 с обеих сторон: 3x = 15.", "Разделим обе стороны на 3: x = 5.", "Проверим: 3 × 5 + 6 = 21."], questions: [
      {text:"2x + 4 = 14. Чему равен x?",options:["3","5","7"],correct:1,why:"Вычитаем 4: 2x = 10. Делим на 2: x = 5."},
      {text:"5x − 10 = 15. Найдите x.",options:["1","3","5"],correct:2,why:"Прибавляем 10: 5x = 25. Делим на 5: x = 5."},
      {text:"Какой шаг сохраняет равенство?",options:["Прибавить 4 только слева","Вычесть 4 с обеих сторон","Разделить обе стороны на ноль"],correct:1,why:"Одинаковое допустимое действие с обеими сторонами сохраняет равенство. Деление на ноль не определено."} ] },
    {id:"percent",title:"Проценты",intro:"Переводим проценты в доли и считаем изменения цены.",rule:"p% от числа N — это N × p / 100. После скидки p% остаётся (100 − p)% исходной цены.",example:"Скидка 15% на цену 200 000 сум",steps:["Скидка: 200 000 × 15 / 100 = 30 000 сум.","Итог: 200 000 − 30 000 = 170 000 сум.","Проверка: 85% × 200 000 = 170 000 сум."],questions:[
      {text:"Сколько составляет 20% от 150?",options:["20","30","120"],correct:1,why:"150 × 20 / 100 = 30."},
      {text:"Цена 100 000 сум, скидка 10%. Сколько заплатить?",options:["10 000 сум","90 000 сум","110 000 сум"],correct:1,why:"Скидка 10 000 сум. Итог: 100 000 − 10 000 = 90 000 сум."},
      {text:"Цена выросла с 80 до 100. На сколько процентов?",options:["20%","25%","80%"],correct:1,why:"Рост 20 делим на исходную цену 80: 20 / 80 × 100 = 25%."}]},
    {id:"probability",title:"Вероятность",intro:"Считаем шансы, когда исходы равновероятны.",rule:"Вероятность = число подходящих исходов / число всех равновероятных исходов. Значение лежит от 0 до 1.",example:"Честный кубик: выпадет чётное число",steps:["Всего 6 равновероятных исходов: 1, 2, 3, 4, 5, 6.","Подходят 3 исхода: 2, 4, 6.","Вероятность: 3 / 6 = 1 / 2 = 50%."],questions:[
      {text:"Шанс получить 6 на честном кубике?",options:["1/2","1/6","1/3"],correct:1,why:"Один подходящий исход из шести: 1/6."},
      {text:"В мешке 3 красных и 2 синих шара. Шар выбирают случайно. Шанс синего?",options:["2/3","3/5","2/5"],correct:2,why:"Всего 5 шаров, синих 2: вероятность 2/5."},
      {text:"Может ли вероятность равняться 1,2?",options:["Да","Нет"],correct:1,why:"Вероятность не больше 1. Значение 1 означает достоверное событие."} ]}
  ],
  uz: [
    {id:"linear",title:"Chiziqli tenglamalar",intro:"Tenglikni saqlagan holda noma’lum sonni topamiz.",rule:"Tenglamaning ikkala tomoniga bir xil amal qo‘llaymiz. Faqat noldan farqli songa bo‘lish mumkin.",example:"3x + 6 = 21",steps:["Ikkala tomondan 6 ni ayiramiz: 3x = 15.","Ikkala tomonni 3 ga bo‘lamiz: x = 5.","Tekshiramiz: 3 × 5 + 6 = 21."],questions:[
      {text:"2x + 4 = 14. x nechaga teng?",options:["3","5","7"],correct:1,why:"4 ni ayiramiz: 2x = 10. 2 ga bo‘lamiz: x = 5."},
      {text:"5x − 10 = 15. x ni toping.",options:["1","3","5"],correct:2,why:"10 ni qo‘shamiz: 5x = 25. 5 ga bo‘lamiz: x = 5."},
      {text:"Qaysi amal tenglikni saqlaydi?",options:["Faqat chap tomonga 4 qo‘shish","Ikkala tomondan 4 ayirish","Ikkala tomonni nolga bo‘lish"],correct:1,why:"Ikkala tomonga bir xil ruxsat etilgan amal qo‘llanadi. Nolga bo‘lish aniqlanmagan."}]},
    {id:"percent",title:"Foizlar",intro:"Foizni ulushga aylantiramiz va narx o‘zgarishini hisoblaymiz.",rule:"N sonning p foizi — N × p / 100. p% chegirmadan keyin boshlang‘ich narxning (100 − p)% qismi qoladi.",example:"200 000 so‘m narxga 15% chegirma",steps:["Chegirma: 200 000 × 15 / 100 = 30 000 so‘m.","Yakuniy narx: 200 000 − 30 000 = 170 000 so‘m.","Tekshiruv: 200 000 ning 85 foizi = 170 000 so‘m."],questions:[
      {text:"150 ning 20 foizi nechaga teng?",options:["20","30","120"],correct:1,why:"150 × 20 / 100 = 30."},
      {text:"Narx 100 000 so‘m, chegirma 10%. Qancha to‘lanadi?",options:["10 000 so‘m","90 000 so‘m","110 000 so‘m"],correct:1,why:"Chegirma 10 000 so‘m. 100 000 − 10 000 = 90 000 so‘m."},
      {text:"Narx 80 dan 100 ga oshdi. Necha foizga?",options:["20%","25%","80%"],correct:1,why:"O‘sish 20. Boshlang‘ich narx 80: 20 / 80 × 100 = 25%."}]},
    {id:"probability",title:"Ehtimollik",intro:"Teng ehtimolli natijalar uchun imkoniyatni hisoblaymiz.",rule:"Ehtimollik = mos natijalar soni / barcha teng ehtimolli natijalar soni. Qiymat 0 dan 1 gacha.",example:"Adolatli o‘yin kubigida juft son tushishi",steps:["6 ta teng ehtimolli natija: 1, 2, 3, 4, 5, 6.","3 tasi mos keladi: 2, 4, 6.","Ehtimollik: 3 / 6 = 1 / 2 = 50%."],questions:[
      {text:"Adolatli kubikda 6 tushish ehtimoli?",options:["1/2","1/6","1/3"],correct:1,why:"Oltita natijadan bittasi mos: 1/6."},
      {text:"Xaltada 3 qizil va 2 ko‘k shar bor. Tasodifiy olingan shar ko‘k bo‘lish ehtimoli?",options:["2/3","3/5","2/5"],correct:2,why:"Jami 5 shar, 2 tasi ko‘k: 2/5."},
      {text:"Ehtimollik 1,2 bo‘lishi mumkinmi?",options:["Ha","Yo‘q"],correct:1,why:"Ehtimollik 1 dan katta bo‘lmaydi. 1 — aniq sodir bo‘ladigan hodisa."}]}
  ]
};
